### ISSUE TITLE
TODO LISTS for v1

### ISSUE THREAD

**Issue by xiaohuoni** [umijs/start#2]
* [x]  download 根绝提供的模版的 git 地址，将模版下载到本地，根绝 package.json 中的 create-umi 配置裁剪文件 
  * https://github.com/umijs/start/commit/f649c7d39657039c96bb7efad7c2cd60721d690e
* [x]  根据模版项目获取页面需要的模版数据
  * 详细逻辑 https://github.com/umijs/start/issues/3
  * https://github.com/umijs/start/commit/6676795afc84449e54a8250341026563f3bbf76b
* [x] 基础的 Generator 只处理配置，其他文件 cpy 。配置包含 umi config 和 package.json
  * https://github.com/umijs/start/commit/e007737197491e2bcf0c467fae7be9f5e2ec4908
  * https://github.com/umijs/start/pull/5
* [x] 项目创建服务，接收一个 config ，返回一个生成的项目文件的临时路径 https://github.com/umijs/start/commit/f98cd9ffb53fc7c7237494458b6b26a978162c8b
* [x] 源码下载服务，接收一个生成的项目文件的临时路径，返回 zip 包，可选择删除被下载的文件 https://github.com/umijs/start/commit/f98cd9ffb53fc7c7237494458b6b26a978162c8b
* [ ] 检测生成的项目是否存在，接收一个生成的项目文件的临时路径，返回是否存在
* [x] 删除在服务器上的项目，比如用户生成完不想下载，重新生成的时候，应该调用该服务，接收一个生成的项目文件的临时路径 https://github.com/umijs/start/commit/f98cd9ffb53fc7c7237494458b6b26a978162c8b

附：create-umi

```json
"create-umi": {
    "ignoreScript": [
      "docker*",
      "functions*",
      "site",
      "generateMock"
    ],
    "ignoreDependencies": [
      "netlify*",
      "serverless"
    ],
    "ignore": [
      ".dockerignore",
      "docker",
      "CNAME",
      "create-umi"
    ]
  }
```

**Comment by chenshuai2144** [comment]
注意下，如果下载了每次 update 就好了，不然服务器会受不了

**Comment by xiaohuoni** [comment]
> 注意下，如果下载了每次 update 就好了，不然服务器会受不了

现在是先把模版库拉到本地的 `.temp-cache` 目录，可以设置只有服务启动的时候拉取，也可以写成手动执行的脚本
用户请求创建的时候用的是本地模版

**Comment by chenshuai2144** [comment]
加模板要重启服务有点蛋疼的， 还是 动态一点吧

**Comment by xiaohuoni** [comment]
不用重启服务，是要执行 update temp。每次请求都 git update 的话，我觉得消耗也不小。这个可以考虑一下，需要的话加一个检测更新逻辑上去。

**Comment by chenshuai2144** [comment]
git update 开销还好点了，加个去抖应该就行了
